name: Compiler le CV LaTeX

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Compiler le CV
        run: |
          xelatex -interaction=nonstopmode CV_Benhirt_FatimaEzzahra_FR.tex
          xelatex -interaction=nonstopmode CV_Benhirt_FatimaEzzahra_FR.tex

      - name: Pousser le PDF généré
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /__w/cv/cv
          git add CV_Benhirt_FatimaEzzahra_FR.pdf
          git diff --cached --quiet || git commit -m "📄 CV mis à jour automatiquement"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
